name=Arduino_OTA
version=0.1.0
author=Arduino
maintainer=Arduino <info@arduino.cc>
sentence=OTA firmware updates over WiFi
category=Communication
architectures=zephyr,zephyr_main,zephyr_contrib
includes=Arduino_OTA.h
depends=WiFi
