name=ArduinoOTA
version=0.1.0
author=Arduino
maintainer=Arduino <info@arduino.cc>
sentence=OTA firmware updates over WiFi
category=Communication
architectures=zephyr,zephyr_main,zephyr_contrib
includes=ArduinoOTA.h
depends=WiFi
