/*
 * Copyright (c) Arduino s.r.l. and/or its affiliated companies
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Hand-maintained LLEXT exports that cannot be auto-generated.
 *
 * Everything else is auto-generated by gen_auto_exports.py (into
 * auto_exports.c) using EDK headers as an allowlist, plus force_exports.txt
 * for symbols not in any header (libc, compiler runtime, etc.).
 *
 * Libc symbols are exported under their plain names; out-of-range BL
 * relocations are handled by CONFIG_LLEXT_ARM_VENEER (automatic veneer
 * stub generation in the kernel).
 */

#include <errno.h>
#include <zephyr/llext/symbol.h>

/*
 * Provide errno access for LLEXT modules.
 *
 * LLEXT modules are compiled with -ftls-model=local-exec which assumes TLS
 * variables reside in the module's own TLS segment; accessing the loader's
 * TLS errno directly from an LLEXT generates __aeabi_read_tp calls that
 * either aren't exported or use the wrong segment offset.
 *
 * This function runs in the loader context where the TLS layout is known,
 * and returns a plain pointer.  LLEXT callers dereference it with no TLS
 * mechanism involved on their side.
 */
int *arduino_errno_ptr(void)
{
	return &errno;
}
EXPORT_SYMBOL(arduino_errno_ptr);
